# Generated by Django 4.2.7 on 2024-01-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0003_alter_streak_id_alter_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='_completion_period',
            field=models.IntegerField(null=True),
        ),
    ]
