# Generated by Django 4.2.7 on 2024-01-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0004_task__completion_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='active_days',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='start_time',
        ),
        migrations.AddField(
            model_name='task',
            name='active_days',
            field=models.CharField(blank=True, choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3, null=True),
        ),
    ]
