# Generated by Django 4.2.7 on 2024-01-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0005_remove_streak_active_days_remove_streak_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='active_days',
        ),
        migrations.AddField(
            model_name='task',
            name='active_days',
            field=models.ManyToManyField(blank=True, null=True, to='streak.enumdays'),
        ),
    ]
