# Generated by Django 4.2.7 on 2024-01-09 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0006_enumdays_remove_task_active_days_task_active_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enumdays',
            old_name='name',
            new_name='day',
        ),
    ]
