# Generated by Django 4.2.7 on 2024-01-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0007_rename_name_enumdays_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enumdays',
            options={'verbose_name_plural': 'EnumDays'},
        ),
        migrations.AlterField(
            model_name='streak',
            name='day_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='_completion_period',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration_per_day',
            field=models.PositiveIntegerField(blank=True, help_text='in minutes', null=True),
        ),
    ]
