# Generated by Django 4.2.7 on 2024-01-09 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0008_alter_enumdays_options_alter_streak_day_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streak',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='task',
            name='_completion_period',
            field=models.PositiveIntegerField(help_text='number of days to perform tasks', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='active_days',
            field=models.ManyToManyField(to='streak.enumdays'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration_per_day',
            field=models.PositiveIntegerField(default=30, help_text='in minutes'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='specific action,                                         eg: read 30 pages (specific), prepare for school (vague)', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
