# Generated by Django 5.0.1 on 2024-01-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streak', '0010_alter_streak_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='_completion_period',
            field=models.PositiveIntegerField(blank=True, help_text='number of days to perform tasks', null=True),
        ),
    ]
